"""initial schema

Revision ID: 3bf9eca3c47f
Revises:
Create Date: 2026-06-11 18:58:51.419599
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bf9eca3c47f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_logs",
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target_user_id", sa.BigInteger(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_logs")),
    )
    op.create_index(
        "ix_admin_logs_action_created", "admin_logs", ["action", "created_at"], unique=False
    )
    op.create_index(op.f("ix_admin_logs_admin_id"), "admin_logs", ["admin_id"], unique=False)
    op.create_index(
        op.f("ix_admin_logs_target_user_id"), "admin_logs", ["target_user_id"], unique=False
    )
    op.create_table(
        "seasons",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("number", name=op.f("uq_seasons_number")),
    )
    op.create_index(op.f("ix_seasons_is_active"), "seasons", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=8), nullable=True),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("xp", sa.BigInteger(), nullable=False),
        sa.Column("rank", sa.String(length=16), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("active_title", sa.String(length=64), nullable=True),
        sa.Column("active_frame", sa.String(length=64), nullable=True),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column("referral_count", sa.Integer(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("ban_reason", sa.Text(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("suspicion_score", sa.Integer(), nullable=False),
        sa.Column("last_daily_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_weekly_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_chest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
            name=op.f("fk_users_referrer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_balance_desc", "users", [sa.literal_column("balance DESC")], unique=False
    )
    op.create_index(op.f("ix_users_referrer_id"), "users", ["referrer_id"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_index("ix_users_xp_desc", "users", [sa.literal_column("xp DESC")], unique=False)
    op.create_table(
        "anti_cheat_logs",
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("rule", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_anti_cheat_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anti_cheat_logs")),
    )
    op.create_index(
        op.f("ix_anti_cheat_logs_user_id"), "anti_cheat_logs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_anti_cheat_rule_created", "anti_cheat_logs", ["rule", "created_at"], unique=False
    )
    op.create_table(
        "battles",
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stake", sa.BigInteger(), nullable=False),
        sa.Column("pot", sa.BigInteger(), nullable=False),
        sa.Column("house_cut", sa.BigInteger(), nullable=False),
        sa.Column("is_team_mode", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("winner_id", sa.BigInteger(), nullable=True),
        sa.Column("winning_team", sa.Integer(), nullable=True),
        sa.Column("season_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_battles_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_battles_season_id_seasons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["users.id"],
            name=op.f("fk_battles_winner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battles")),
    )
    op.create_index(op.f("ix_battles_chat_id"), "battles", ["chat_id"], unique=False)
    op.create_index("ix_battles_chat_status", "battles", ["chat_id", "status"], unique=False)
    op.create_index(op.f("ix_battles_mode"), "battles", ["mode"], unique=False)
    op.create_index("ix_battles_mode_status", "battles", ["mode", "status"], unique=False)
    op.create_index(op.f("ix_battles_season_id"), "battles", ["season_id"], unique=False)
    op.create_index(op.f("ix_battles_status"), "battles", ["status"], unique=False)
    op.create_index(op.f("ix_battles_winner_id"), "battles", ["winner_id"], unique=False)
    op.create_table(
        "case_openings",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("case_code", sa.String(length=32), nullable=False),
        sa.Column("rarity", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("reward_kind", sa.String(length=16), nullable=False),
        sa.Column("reward_coins", sa.Integer(), nullable=False),
        sa.Column("reward_item_code", sa.String(length=64), nullable=True),
        sa.Column("reward_label", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_case_openings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_openings")),
    )
    op.create_index(
        "ix_case_openings_user_created", "case_openings", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "clans",
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("tag", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("emblem", sa.String(length=16), nullable=True),
        sa.Column("leader_id", sa.BigInteger(), nullable=False),
        sa.Column("treasury", sa.BigInteger(), nullable=False),
        sa.Column("total_points", sa.BigInteger(), nullable=False),
        sa.Column("wars_won", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["leader_id"], ["users.id"], name=op.f("fk_clans_leader_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clans")),
    )
    op.create_index(op.f("ix_clans_name"), "clans", ["name"], unique=True)
    op.create_index(
        "ix_clans_points_desc", "clans", [sa.literal_column("total_points DESC")], unique=False
    )
    op.create_index(op.f("ix_clans_tag"), "clans", ["tag"], unique=True)
    op.create_table(
        "hall_of_fame",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("placement", sa.Integer(), nullable=False),
        sa.Column("season_points", sa.BigInteger(), nullable=False),
        sa.Column("badge_code", sa.String(length=64), nullable=True),
        sa.Column("reward_coins", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_hall_of_fame_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_hall_of_fame_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hall_of_fame")),
    )
    op.create_index(
        "ix_hall_of_fame_season_placement", "hall_of_fame", ["season_id", "placement"], unique=False
    )
    op.create_table(
        "inventory_items",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_inventory_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
    )
    op.create_index(
        "uq_inventory_item", "inventory_items", ["user_id", "kind", "item_code"], unique=True
    )
    op.create_table(
        "reward_claims",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reward_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("streak_day", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reward_claims_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reward_claims")),
    )
    op.create_index(
        "ix_reward_claims_user_type",
        "reward_claims",
        ["user_id", "reward_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "season_participants",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("season_points", sa.BigInteger(), nullable=False),
        sa.Column("season_wins", sa.Integer(), nullable=False),
        sa.Column("season_coins", sa.BigInteger(), nullable=False),
        sa.Column("final_rank", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_season_participants_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_season_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season_participants")),
    )
    op.create_index(
        "ix_season_participants_points",
        "season_participants",
        ["season_id", sa.literal_column("season_points DESC")],
        unique=False,
    )
    op.create_index(
        "uq_season_participant", "season_participants", ["season_id", "user_id"], unique=True
    )
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(op.f("ix_transactions_reference"), "transactions", ["reference"], unique=False)
    op.create_index(
        "ix_transactions_type_created", "transactions", ["type", "created_at"], unique=False
    )
    op.create_index(
        "ix_transactions_user_created", "transactions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_achievements",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_achievements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievements")),
    )
    op.create_index("uq_user_achievement", "user_achievements", ["user_id", "code"], unique=True)
    op.create_table(
        "user_powerups",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("charges", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_powerups_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_powerups")),
    )
    op.create_index("uq_user_powerup", "user_powerups", ["user_id", "type"], unique=True)
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("total_games", sa.BigInteger(), nullable=False),
        sa.Column("wins", sa.BigInteger(), nullable=False),
        sa.Column("losses", sa.BigInteger(), nullable=False),
        sa.Column("draws", sa.BigInteger(), nullable=False),
        sa.Column("biggest_win", sa.BigInteger(), nullable=False),
        sa.Column("biggest_loss", sa.BigInteger(), nullable=False),
        sa.Column("total_wagered", sa.BigInteger(), nullable=False),
        sa.Column("coins_earned", sa.BigInteger(), nullable=False),
        sa.Column("coins_spent", sa.BigInteger(), nullable=False),
        sa.Column("tournaments_won", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_stats_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_stats")),
    )
    op.create_table(
        "battle_participants",
        sa.Column("battle_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("team", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("rolls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("has_rolled", sa.Boolean(), nullable=False),
        sa.Column("is_winner", sa.Boolean(), nullable=False),
        sa.Column("payout", sa.BigInteger(), nullable=False),
        sa.Column("powerups_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battles.id"],
            name=op.f("fk_battle_participants_battle_id_battles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_battle_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battle_participants")),
    )
    op.create_index("ix_battle_participants_user", "battle_participants", ["user_id"], unique=False)
    op.create_index(
        "uq_battle_participant", "battle_participants", ["battle_id", "user_id"], unique=True
    )
    op.create_table(
        "clan_members",
        sa.Column("clan_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("contributed", sa.BigInteger(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clans.id"],
            name=op.f("fk_clan_members_clan_id_clans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_clan_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clan_members")),
        sa.UniqueConstraint("user_id", name=op.f("uq_clan_members_user_id")),
    )
    op.create_index("ix_clan_members_clan_role", "clan_members", ["clan_id", "role"], unique=False)
    op.create_table(
        "clan_wars",
        sa.Column("clan_a_id", sa.BigInteger(), nullable=False),
        sa.Column("clan_b_id", sa.BigInteger(), nullable=False),
        sa.Column("clan_a_score", sa.Integer(), nullable=False),
        sa.Column("clan_b_score", sa.Integer(), nullable=False),
        sa.Column("prize_pool", sa.BigInteger(), nullable=False),
        sa.Column("winner_clan_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["clan_a_id"],
            ["clans.id"],
            name=op.f("fk_clan_wars_clan_a_id_clans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["clan_b_id"],
            ["clans.id"],
            name=op.f("fk_clan_wars_clan_b_id_clans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_clan_id"],
            ["clans.id"],
            name=op.f("fk_clan_wars_winner_clan_id_clans"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clan_wars")),
    )
    op.create_table(
        "lobbies",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("stake", sa.BigInteger(), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("min_players", sa.Integer(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("battle_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battles.id"],
            name=op.f("fk_lobbies_battle_id_battles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["users.id"], name=op.f("fk_lobbies_host_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lobbies")),
    )
    op.create_index(op.f("ix_lobbies_chat_id"), "lobbies", ["chat_id"], unique=False)
    op.create_index(op.f("ix_lobbies_code"), "lobbies", ["code"], unique=True)
    op.create_index("ix_lobbies_mode_stake", "lobbies", ["mode", "stake"], unique=False)
    op.create_index(op.f("ix_lobbies_status"), "lobbies", ["status"], unique=False)
    op.create_index("ix_lobbies_status_private", "lobbies", ["status", "is_private"], unique=False)
    op.create_table(
        "lobby_members",
        sa.Column("lobby_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("team", sa.Integer(), nullable=True),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["lobby_id"],
            ["lobbies.id"],
            name=op.f("fk_lobby_members_lobby_id_lobbies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_lobby_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lobby_members")),
    )
    op.create_index("uq_lobby_member", "lobby_members", ["lobby_id", "user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_lobby_member", table_name="lobby_members")
    op.drop_table("lobby_members")
    op.drop_index("ix_lobbies_status_private", table_name="lobbies")
    op.drop_index(op.f("ix_lobbies_status"), table_name="lobbies")
    op.drop_index("ix_lobbies_mode_stake", table_name="lobbies")
    op.drop_index(op.f("ix_lobbies_code"), table_name="lobbies")
    op.drop_index(op.f("ix_lobbies_chat_id"), table_name="lobbies")
    op.drop_table("lobbies")
    op.drop_table("clan_wars")
    op.drop_index("ix_clan_members_clan_role", table_name="clan_members")
    op.drop_table("clan_members")
    op.drop_index("uq_battle_participant", table_name="battle_participants")
    op.drop_index("ix_battle_participants_user", table_name="battle_participants")
    op.drop_table("battle_participants")
    op.drop_table("user_stats")
    op.drop_index("uq_user_powerup", table_name="user_powerups")
    op.drop_table("user_powerups")
    op.drop_index("uq_user_achievement", table_name="user_achievements")
    op.drop_table("user_achievements")
    op.drop_index("ix_transactions_user_created", table_name="transactions")
    op.drop_index("ix_transactions_type_created", table_name="transactions")
    op.drop_index(op.f("ix_transactions_reference"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("uq_season_participant", table_name="season_participants")
    op.drop_index("ix_season_participants_points", table_name="season_participants")
    op.drop_table("season_participants")
    op.drop_index("ix_reward_claims_user_type", table_name="reward_claims")
    op.drop_table("reward_claims")
    op.drop_index("uq_inventory_item", table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index("ix_hall_of_fame_season_placement", table_name="hall_of_fame")
    op.drop_table("hall_of_fame")
    op.drop_index(op.f("ix_clans_tag"), table_name="clans")
    op.drop_index("ix_clans_points_desc", table_name="clans")
    op.drop_index(op.f("ix_clans_name"), table_name="clans")
    op.drop_table("clans")
    op.drop_index("ix_case_openings_user_created", table_name="case_openings")
    op.drop_table("case_openings")
    op.drop_index(op.f("ix_battles_winner_id"), table_name="battles")
    op.drop_index(op.f("ix_battles_status"), table_name="battles")
    op.drop_index(op.f("ix_battles_season_id"), table_name="battles")
    op.drop_index("ix_battles_mode_status", table_name="battles")
    op.drop_index(op.f("ix_battles_mode"), table_name="battles")
    op.drop_index("ix_battles_chat_status", table_name="battles")
    op.drop_index(op.f("ix_battles_chat_id"), table_name="battles")
    op.drop_table("battles")
    op.drop_index("ix_anti_cheat_rule_created", table_name="anti_cheat_logs")
    op.drop_index(op.f("ix_anti_cheat_logs_user_id"), table_name="anti_cheat_logs")
    op.drop_table("anti_cheat_logs")
    op.drop_index("ix_users_xp_desc", table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referrer_id"), table_name="users")
    op.drop_index("ix_users_balance_desc", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_seasons_is_active"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_admin_logs_target_user_id"), table_name="admin_logs")
    op.drop_index(op.f("ix_admin_logs_admin_id"), table_name="admin_logs")
    op.drop_index("ix_admin_logs_action_created", table_name="admin_logs")
    op.drop_table("admin_logs")
    # ### end Alembic commands ###
